import { createHash, randomBytes, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile } from "node:fs/promises";
import { constants } from "node:fs";
import { join, resolve } from "node:path";
import { SQL } from "bun";

export interface LocalInstallationRequest { tenantId: string; hostname: string; administratorEmail: string }
export interface TemporalNamespaces { create(input: { tenantId: string; namespace: string; secretDirectory: string }): Promise<void> }
export interface LocalProvisionerOptions { controlDatabaseUrl: string; productDatabaseAdminUrl: string; ordinaryConfigPath: string; archiveConfigPath: string; secretsRoot: string; temporal: TemporalNamespaces }
export interface LocalInstallation { tenantId: string; installationId: string; productDatabase: string; productRole: string; temporalNamespace: string; secretBundlePath: string; state: "ready" | "partial" }
interface S3Identity { name: string; credentials: Array<{ accessKey: string; secretKey: string }> }
interface S3Config { identities: S3Identity[] }
interface SecretBundle { installationId: string; tenantId: string; product: { database: string; role: string; credentialsPath: string }; storage: { ordinaryCredentialsPath: string; archiveCredentialsPath: string }; application: { jwtSecretPath: string; encryptionSecretPath: string }; temporal: { namespace: string; credentialsPath: string }; invitationId: string }
const quote = (identifier: string) => `"${identifier.replaceAll('"', '""')}"`;
const localName = (prefix: string, tenantId: string) => `${prefix}_${createHash("sha256").update(tenantId).digest("hex").slice(0, 20)}`;
const secret = () => randomBytes(32).toString("base64url");
const stored = (record: Record<string, string>, field: string): string => { const value = record[field]; if (!value) throw new Error(`Installation record has no ${field}.`); return value; };
function assertRequest(request: LocalInstallationRequest): void { if (!/^tenant-\d{2}$/.test(request.tenantId)) throw new Error("Local provisioner requires a generated tenant-XX identity."); if (!/^[a-z0-9][a-z0-9.-]{0,252}$/.test(request.hostname)) throw new Error("Installation hostname is malformed."); if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(request.administratorEmail)) throw new Error("First administrator email is malformed."); }
async function privateDirectory(path: string): Promise<void> { try { const status = await lstat(path); if (!status.isDirectory() || status.isSymbolicLink() || status.uid !== process.getuid?.() || (status.mode & 0o077) !== 0) throw new Error("Provisioner secret directory must be private and owned by this user."); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; const parent = resolve(path, ".."); const parentStatus = await lstat(parent); if (!parentStatus.isDirectory() || parentStatus.isSymbolicLink() || parentStatus.uid !== process.getuid?.() || (parentStatus.mode & 0o077) !== 0) throw new Error("Provisioner secret parent must be private and owned by this user."); await mkdir(path, { mode: 0o700 }); } }
async function privateFile(path: string, value: string): Promise<void> { try { const status = await lstat(path); if (!status.isFile() || status.isSymbolicLink() || status.uid !== process.getuid?.() || (status.mode & 0o077) !== 0) throw new Error("Provisioner secret file must be private and owned by this user."); } catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; const handle = await open(path, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600); try { await handle.writeFile(value); } finally { await handle.close(); } } }
async function writePrivateJson(path: string, value: unknown): Promise<void> { await privateFile(path, `${JSON.stringify(value)}\n`); }
async function writePrivateText(path: string): Promise<void> { await privateFile(path, `${secret()}\n`); }
async function identity(path: string, tenantId: string): Promise<{ accessKey: string; secretKey: string }> { const config = JSON.parse(await readFile(path, "utf8")) as S3Config; const credential = config.identities.find((entry) => entry.name === tenantId)?.credentials[0]; if (!credential?.accessKey || !credential.secretKey) throw new Error(`Storage identity for ${tenantId} is unavailable.`); return { accessKey: credential.accessKey, secretKey: credential.secretKey }; }
async function bundle(path: string): Promise<SecretBundle> { return JSON.parse(await readFile(path, "utf8")) as SecretBundle; }

/** Local C12 provisioner. Its control database has only public identifiers and private bundle paths. */
export class LocalFactoryProvisioner {
  private readonly control: SQL;
  private readonly productAdmin: SQL;
  constructor(private readonly options: LocalProvisionerOptions) { this.control = new SQL(options.controlDatabaseUrl, { max: 2 }); this.productAdmin = new SQL(options.productDatabaseAdminUrl, { max: 2 }); }
  async close(): Promise<void> { await this.control.close(); await this.productAdmin.close(); }
  async setup(): Promise<void> { await this.control.unsafe("CREATE TABLE IF NOT EXISTS factory_installations (tenant_id text PRIMARY KEY, installation_id text NOT NULL UNIQUE, hostname text NOT NULL UNIQUE, administrator_email text NOT NULL, product_database text NOT NULL UNIQUE, product_role text NOT NULL UNIQUE, temporal_namespace text NOT NULL UNIQUE, secret_bundle_path text NOT NULL, state text NOT NULL CHECK (state IN ('partial','ready')), current_step text NOT NULL, invitation_id text NOT NULL)"); }
  async provision(request: LocalInstallationRequest): Promise<LocalInstallation> {
    assertRequest(request); await this.setup();
    const database = localName("factory_product", request.tenantId), role = localName("factory_role", request.tenantId), namespace = request.tenantId, directory = resolve(this.options.secretsRoot, request.tenantId);
    const existing = (await this.control`SELECT tenant_id, installation_id, hostname, administrator_email, product_database, product_role, temporal_namespace, secret_bundle_path, state, current_step, invitation_id FROM factory_installations WHERE tenant_id = ${request.tenantId}`)[0] as Record<string, string> | undefined;
    if (existing?.hostname && (existing.hostname !== request.hostname || existing.administrator_email !== request.administratorEmail)) throw new Error("Provisioning request conflicts with its persisted tenant identity.");
    if (existing?.state === "ready") { await this.verifyReady(existing); await this.options.temporal.create({ tenantId: stored(existing, "tenant_id"), namespace: stored(existing, "temporal_namespace"), secretDirectory: stored(existing, "secret_bundle_path") }); return this.ready(existing); }
    const installationId = existing?.installation_id ?? randomUUID(), invitationId = existing?.invitation_id ?? randomUUID();
    await this.control`INSERT INTO factory_installations(tenant_id, installation_id, hostname, administrator_email, product_database, product_role, temporal_namespace, secret_bundle_path, state, current_step, invitation_id) VALUES (${request.tenantId}, ${installationId}, ${request.hostname}, ${request.administratorEmail}, ${database}, ${role}, ${namespace}, ${directory}, 'partial', 'recorded', ${invitationId}) ON CONFLICT (tenant_id) DO NOTHING`;
    const persisted = (await this.control`SELECT installation_id, invitation_id, product_database, product_role, temporal_namespace, secret_bundle_path FROM factory_installations WHERE tenant_id = ${request.tenantId}`)[0] as Record<string, string> | undefined; if (!persisted || persisted.product_database !== database || persisted.product_role !== role || persisted.temporal_namespace !== namespace || persisted.secret_bundle_path !== directory) throw new Error("Concurrent provisioning record conflicts with its deterministic tenant resources.");
    const stableInstallationId = stored(persisted, "installation_id"), stableInvitationId = stored(persisted, "invitation_id");
    await privateDirectory(directory);
    const bundlePath = join(directory, "installation.json"), productCredentialsPath = join(directory, "product-database.json"), ordinaryPath = join(directory, "ordinary-storage.json"), archivePath = join(directory, "archive-storage.json"), jwtPath = join(directory, "application-jwt-secret"), encryptionPath = join(directory, "application-encryption-secret"), temporalPath = join(directory, "temporal.json");
    await writePrivateJson(productCredentialsPath, { role, password: secret() }); await writePrivateJson(ordinaryPath, await identity(this.options.ordinaryConfigPath, request.tenantId)); await writePrivateJson(archivePath, await identity(this.options.archiveConfigPath, request.tenantId)); await writePrivateText(jwtPath); await writePrivateText(encryptionPath);
    await writePrivateJson(bundlePath, { installationId: stableInstallationId, tenantId: request.tenantId, product: { database, role, credentialsPath: productCredentialsPath }, storage: { ordinaryCredentialsPath: ordinaryPath, archiveCredentialsPath: archivePath }, application: { jwtSecretPath: jwtPath, encryptionSecretPath: encryptionPath }, temporal: { namespace, credentialsPath: temporalPath }, invitationId: stableInvitationId } satisfies SecretBundle);
    const product = await bundle(bundlePath); const credentials = JSON.parse(await readFile(product.product.credentialsPath, "utf8")) as { password: string }; if (!/^[A-Za-z0-9_-]{43}$/.test(credentials.password)) throw new Error("Product credential has an invalid format.");
    const roleExists = (await this.productAdmin`SELECT 1 FROM pg_roles WHERE rolname = ${role}`)[0]; if (!roleExists) await this.productAdmin.unsafe(`CREATE ROLE ${quote(role)} LOGIN PASSWORD '${credentials.password}'`);
    const databaseOwner = (await this.productAdmin`SELECT pg_get_userbyid(datdba) AS owner FROM pg_database WHERE datname = ${database}`)[0] as { owner: string } | undefined;
    if (databaseOwner && databaseOwner.owner !== role) throw new Error("Product database exists with an untrusted owner.");
    if (!databaseOwner) await this.productAdmin.unsafe(`CREATE DATABASE ${quote(database)} OWNER ${quote(role)}`);
    await this.productAdmin.unsafe(`REVOKE ALL ON DATABASE ${quote(database)} FROM PUBLIC`);
    await this.productAdmin.unsafe(`GRANT CONNECT, TEMPORARY ON DATABASE ${quote(database)} TO ${quote(role)}`);
    await this.control`UPDATE factory_installations SET current_step = 'database' WHERE tenant_id = ${request.tenantId}`;
    await this.options.temporal.create({ tenantId: request.tenantId, namespace, secretDirectory: directory });
    await this.control`UPDATE factory_installations SET state = 'ready', current_step = 'invitation' WHERE tenant_id = ${request.tenantId}`;
    return { tenantId: request.tenantId, installationId: stableInstallationId, productDatabase: database, productRole: role, temporalNamespace: namespace, secretBundlePath: directory, state: "ready" };
  }
  private ready(existing: Record<string, string>): LocalInstallation { return { tenantId: stored(existing, "tenant_id"), installationId: stored(existing, "installation_id"), productDatabase: stored(existing, "product_database"), productRole: stored(existing, "product_role"), temporalNamespace: stored(existing, "temporal_namespace"), secretBundlePath: stored(existing, "secret_bundle_path"), state: "ready" }; }
  private async verifyReady(existing: Record<string, string>): Promise<void> { const directory = stored(existing, "secret_bundle_path"); await privateDirectory(directory); for (const file of ["installation.json", "product-database.json", "ordinary-storage.json", "archive-storage.json", "application-jwt-secret", "application-encryption-secret", "temporal.json", "temporal-token"]) { const status = await lstat(join(directory, file)); if (!status.isFile() || status.isSymbolicLink() || status.uid !== process.getuid?.() || (status.mode & 0o077) !== 0) throw new Error("Ready installation has an unsafe secret bundle."); } const database = stored(existing, "product_database"), role = stored(existing, "product_role"); const owner = (await this.productAdmin`SELECT pg_get_userbyid(datdba) AS owner FROM pg_database WHERE datname = ${database}`)[0] as { owner: string } | undefined; if (!owner || owner.owner !== role) throw new Error("Ready installation has an untrusted product database."); await this.productAdmin.unsafe(`REVOKE ALL ON DATABASE ${quote(database)} FROM PUBLIC`); await this.productAdmin.unsafe(`GRANT CONNECT, TEMPORARY ON DATABASE ${quote(database)} TO ${quote(role)}`); }
}
