import { createSign, generateKeyPairSync, randomUUID } from "node:crypto";
import { execFile as execFileCallback, spawn } from "node:child_process";
import { copyFile, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { request as httpsRequest } from "node:https";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { afterAll, beforeAll, expect, test } from "bun:test";

const execFile = promisify(execFileCallback); const keys = generateKeyPairSync("rsa", { modulusLength: 2048 });
let root: string; let port: number; let child: ReturnType<typeof spawn>;
const bun = "/tmp/factory-tools/bun-1.3.14/bun-linux-x64/bun";
const encode = (value: unknown) => Buffer.from(JSON.stringify(value)).toString("base64url");
const token = (subject: string, scope: string[]) => { const input = `${encode({ alg: "RS256", kid: "test" })}.${encode({ sub: subject, iss: "factory-test", aud: "factory-pool", exp: Math.floor(Date.now() / 1000) + 60, scope })}`; const signer = createSign("RSA-SHA256"); signer.update(input); signer.end(); return `${input}.${signer.sign(keys.privateKey).toString("base64url")}`; };
async function certificate(name: string): Promise<void> { await execFile("openssl", ["req", "-newkey", "rsa:2048", "-nodes", "-keyout", join(root, `${name}.key`), "-out", join(root, `${name}.csr`), "-subj", `/CN=${name}`]); await execFile("openssl", ["x509", "-req", "-in", join(root, `${name}.csr`), "-CA", join(root, "ca.crt"), "-CAkey", join(root, "ca.key"), "-CAcreateserial", "-out", join(root, `${name}.crt`), "-days", "1"]); }
const call = async (identity: string, jwt: string, path: string, method = "GET", body?: unknown): Promise<number> => { const options = { host: "127.0.0.1", port, servername: "pool", method, path, ca: await readFile(join(root, "ca.crt")), cert: await readFile(join(root, `${identity}.crt`)), key: await readFile(join(root, `${identity}.key`)), headers: { authorization: `Bearer ${jwt}`, "content-type": "application/json" } }; return new Promise((resolve, reject) => { const request = httpsRequest(options, response => { response.resume(); response.on("end", () => resolve(response.statusCode ?? 0)); }); request.on("error", reject); if (body !== undefined) request.write(JSON.stringify(body)); request.end(); }); };

beforeAll(async () => {
  root = await mkdtemp(join(tmpdir(), "factory-pool-node-mtls-")); await execFile("openssl", ["req", "-x509", "-newkey", "rsa:2048", "-nodes", "-keyout", join(root, "ca.key"), "-out", join(root, "ca.crt"), "-subj", "/CN=factory-test-ca", "-days", "1"]); for (const name of ["pool", "tenant-one", "tenant-two", "supervisor-one"]) await certificate(name);
  const bundle = join(root, "server.mjs"); await execFile(bun, ["build", "src/factory/pool/service-server.ts", "--target", "node", "--format", "esm", "--sourcemap=inline", `--outfile=${bundle}`]);
  if (process.env.FACTORY_POOL_NODE_V8_BUNDLE) await copyFile(bundle, process.env.FACTORY_POOL_NODE_V8_BUNDLE);
  const runner = join(root, "runner.mjs"); const configuration = { certificatePath: join(root, "pool.crt"), privateKeyPath: join(root, "pool.key"), certificateAuthorityPath: join(root, "ca.crt"), publicKey: keys.publicKey.export({ type: "pkcs1", format: "pem" }).toString() };
  await writeFile(runner, `import { startPoolAdmissionHttps } from ${JSON.stringify(`file://${bundle}`)}; const c=JSON.parse(process.env.FACTORY_POOL_TEST_CONFIG); const service={setup:async()=>{},request:async(_,input)=>({status:'queued',reservationId:input.reservationId}),status:async(p,id)=>{if(p.tenantId!=='tenant-01')throw Error('foreign');return {tenantId:p.tenantId,reservationId:id};},acknowledgeStart:async()=>({}),renew:async()=>({}),cancel:async()=>({}),confirmStopped:async()=>({}),confirmReimage:async()=>({})}; const server=await startPoolAdmissionHttps({host:'127.0.0.1',port:0,certificatePath:c.certificatePath,privateKeyPath:c.privateKeyPath,certificateAuthorityPath:c.certificateAuthorityPath,identities:{tenants:{'tenant-one':{tenantId:'tenant-01',tokenSubject:'tenant-one'},'tenant-two':{tenantId:'tenant-02',tokenSubject:'tenant-two'}},supervisors:{'supervisor-one':{supervisorId:'supervisor-a',tokenSubject:'supervisor-one',hostIds:['gpu-a']}}},tokens:{issuer:'factory-test',audience:'factory-pool',publicKeys:{test:c.publicKey}},service}); console.log(server.port); process.on('SIGTERM',async()=>{await server.close();process.exit(0)});`);
  child = spawn("node", [runner], { env: { ...process.env, FACTORY_POOL_TEST_CONFIG: JSON.stringify(configuration) }, stdio: ["ignore", "pipe", "pipe"] }); port = await new Promise((resolve, reject) => { let output = ""; child.stdout!.on("data", value => { output += value; const match = output.match(/^(\d+)/); if (match) resolve(Number(match[1])); }); child.once("error", reject); child.stderr!.on("data", value => reject(new Error(value.toString()))); });
});
afterAll(async () => { child?.kill("SIGTERM"); await rm(root, { recursive: true, force: true }); });
test("denies foreign certificate/token identity at real mTLS HTTPS ingress", async () => { const own = token("tenant-one", ["pool:tenant:tenant-01", "pool:grant:tenant-01:g"]); const reservationId = `r-${randomUUID()}`; expect(await call("tenant-one", own, "/v1/pool/requests", "POST", { reservationId, grantRevision: 1, grantScope: "tenant-01:g", resources: { cpu: 1 }, admissionDeadline: new Date(Date.now() + 60_000).toISOString() })).toBe(200); expect(await call("tenant-one", own, `/v1/pool/requests/${reservationId}`)).toBe(200); for (const action of ["acknowledge-start", "renew", "cancel"]) expect(await call("tenant-one", own, `/v1/pool/requests/${reservationId}/${action}`, "POST", { grantRevision: 1, allocationGeneration: 1, allocationToken: "token" })).toBe(200); const supervisor = token("supervisor-one", ["pool:supervisor:supervisor-a"]); expect(await call("supervisor-one", supervisor, "/v1/pool/supervisor/stop", "POST", { reservationId, holderGeneration: 1, hostId: "gpu-a" })).toBe(200); expect(await call("supervisor-one", supervisor, "/v1/pool/supervisor/reimage", "POST", { reservationId, holderGeneration: 1, hostId: "gpu-a", receipt: "receipt" })).toBe(200); expect(await call("tenant-one", own, "/nope")).toBe(404); expect(await call("tenant-two", token("tenant-two", ["pool:tenant:tenant-02"]), "/v1/pool/requests/x")).toBe(403); expect(await call("tenant-one", token("tenant-two", ["pool:tenant:tenant-02"]), "/v1/pool/requests/x")).toBe(403); });
