import { digestBytes, digestObject } from "../../extensions/v4/blobs";
import { factoryGitCommitId, factoryGitTreeId, type FactoryGitIdentity } from "../git-objects";
import {
  assertFactoryGitHubPublicationRequest,
  FACTORY_GITHUB_PUBLICATION_SCHEMA_VERSION,
  FactoryGitHubError,
  type FactoryGitHubPublicationPlan,
  type FactoryGitHubPublicationRequest,
} from "../release-github";
import { referenceCodeFilesDigest, type ReferenceCodeFile, type ReferenceCodeSnapshot } from "./snapshot";

/**
 * Freezes a generated candidate into one complete, named Git tree and commit.
 *
 * The freeze is where a candidate stops being a proposal. It produces the exact object the
 * publication will later create — the same tree SHA, the same commit SHA, the same parent — and
 * validates it with the publication adapter's own rules, so the shape that passes here is the shape
 * that passes at release. There is deliberately no second copy of "which paths are allowed" or
 * "which files are protected": {@link assertFactoryGitHubPublicationRequest} owns those, and a rule
 * that only the freeze knew would be a rule the release could not enforce.
 *
 * A frozen candidate is complete. It lists every file of the resulting tree, inherits nothing from
 * a base tree, and names the pinned base commit as its only parent.
 */

export const REFERENCE_CODE_FREEZE_SCHEMA_VERSION = "factory.reference-code-candidate.v1" as const;

/** The identity every reference-code commit is authored under. Fixed, so the SHA is reproducible. */
export const REFERENCE_CODE_COMMIT_AUTHOR = Object.freeze({
  name: "EZCorp Factory",
  email: "factory@ezcorp.invalid",
  timezone: "+0000",
} as const);

export type ReferenceCodeFreezeErrorCode =
  | "reference_code_candidate_incomplete"
  | "reference_code_candidate_unchanged"
  | "reference_code_candidate_invalid"
  | "reference_code_candidate_base_mismatch";

export class ReferenceCodeFreezeError extends Error {
  constructor(readonly code: ReferenceCodeFreezeErrorCode, readonly detail?: string) {
    super(detail ? `${code}: ${detail}` : code);
    this.name = "ReferenceCodeFreezeError";
  }
}

export interface ReferenceCodeFreezeInput {
  readonly snapshot: ReferenceCodeSnapshot;
  /** The complete resulting tree. Not a patch, and not merged with the base here. */
  readonly files: readonly ReferenceCodeFile[];
  readonly repositoryId: number;
  readonly baseBranch: string;
  readonly issue: string;
  readonly title: string;
  readonly allowedPaths: readonly string[];
  readonly protectedPaths: readonly string[];
  /** A recorded input, never a clock read: a moving timestamp moves the commit SHA. */
  readonly authoredAtSeconds: number;
  readonly candidateGeneration: number;
}

export interface ReferenceCodeCandidate {
  readonly schemaVersion: typeof REFERENCE_CODE_FREEZE_SCHEMA_VERSION;
  readonly candidateGeneration: number;
  readonly baseSha: string;
  readonly treeSha: string;
  readonly commitSha: string;
  /** Content identity of the complete tree, independent of git. */
  readonly filesDigest: string;
  /** Paths whose bytes differ from the snapshot, added or removed. Sorted. */
  readonly changedPaths: readonly string[];
  /** Exactly what the release adapter will be handed, already validated by its own rules. */
  readonly publication: FactoryGitHubPublicationRequest;
  readonly plan: FactoryGitHubPublicationPlan;
}

function identity(atSeconds: number): FactoryGitIdentity {
  return { ...REFERENCE_CODE_COMMIT_AUTHOR, atSeconds };
}

/**
 * The pull-request body, which states the exact base that was tested.
 *
 * The wording matters: opening a pull request says nothing about the branch's current head or
 * about a merged tree. Only the named parent commit was ever checked.
 */
export function referenceCodePullRequestBody(input: {
  readonly issue: string;
  readonly baseSha: string;
  readonly baseBranch: string;
  readonly candidateGeneration: number;
}): string {
  return [
    "Generated by the EZCorp reference code factory (`reference.code.v1`).",
    "",
    `Request: ${input.issue}`,
    "",
    `Tested base: \`${input.baseSha}\` on \`${input.baseBranch}\`.`,
    `Candidate generation: ${input.candidateGeneration}.`,
    "",
    "The protected checks ran against that exact base commit. They say nothing about the current head of the base branch, or about the result of merging this branch into it.",
  ].join("\n");
}

/** Paths whose content differs between two complete trees, including additions and removals. */
export function referenceCodeChangedPaths(
  base: readonly ReferenceCodeFile[],
  candidate: readonly ReferenceCodeFile[],
): readonly string[] {
  const before = new Map(base.map(file => [file.path, `${file.mode} ${digestBytes(file.content)}`]));
  const after = new Map(candidate.map(file => [file.path, `${file.mode} ${digestBytes(file.content)}`]));
  const changed = new Set<string>();
  for (const [path, value] of after) if (before.get(path) !== value) changed.add(path);
  for (const path of before.keys()) if (!after.has(path)) changed.add(path);
  return [...changed].sort();
}

/**
 * Seals the candidate, or refuses it.
 *
 * Three refusals happen before the publication rules even run, because they are about the
 * candidate's relationship to its snapshot rather than about its contents: a tree that changed
 * nothing is not a candidate, a tree that dropped the dependency lock is not complete, and a
 * generation outside the declared bound is not a candidate this contract authorized.
 */
export function freezeReferenceCodeCandidate(input: ReferenceCodeFreezeInput): ReferenceCodeCandidate {
  const { snapshot } = input;
  if (input.files.length < 1) throw new ReferenceCodeFreezeError("reference_code_candidate_incomplete", "empty tree");
  const changedPaths = referenceCodeChangedPaths(snapshot.files, input.files);
  if (changedPaths.length === 0) throw new ReferenceCodeFreezeError("reference_code_candidate_unchanged");
  const lock = input.files.find(file => file.path === snapshot.dependencyLockPath);
  if (!lock) throw new ReferenceCodeFreezeError("reference_code_candidate_incomplete", snapshot.dependencyLockPath);

  const sorted = [...input.files].sort((left, right) => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0));
  const author = identity(input.authoredAtSeconds);
  let treeSha: string;
  let commitSha: string;
  try {
    treeSha = factoryGitTreeId(sorted.map(file => ({ path: file.path, mode: file.mode, content: file.content })));
    commitSha = factoryGitCommitId({
      treeId: treeSha,
      parents: [snapshot.baseSha],
      author,
      committer: author,
      message: `${input.title}\n\nCandidate generation ${input.candidateGeneration} for base ${snapshot.baseSha}.\n`,
    });
  } catch (error) {
    throw new ReferenceCodeFreezeError("reference_code_candidate_invalid", String((error as Error).message));
  }

  const body = referenceCodePullRequestBody({
    issue: input.issue,
    baseSha: snapshot.baseSha,
    baseBranch: input.baseBranch,
    candidateGeneration: input.candidateGeneration,
  });
  const publication: FactoryGitHubPublicationRequest = {
    schemaVersion: FACTORY_GITHUB_PUBLICATION_SCHEMA_VERSION,
    repositoryId: input.repositoryId,
    baseBranch: input.baseBranch,
    baseSha: snapshot.baseSha,
    treeSha,
    commitSha,
    commitMessage: `${input.title}\n\nCandidate generation ${input.candidateGeneration} for base ${snapshot.baseSha}.\n`,
    author,
    committer: author,
    title: input.title,
    body,
    titleBodyDigest: `sha256:${digestObject({ title: input.title, body })}`,
    dependencyLockPath: snapshot.dependencyLockPath,
    dependencyLockDigest: `sha256:${digestBytes(lock.content)}`,
    protectedPaths: [...input.protectedPaths],
    allowedPaths: [...input.allowedPaths],
    files: sorted.map(file => ({ path: file.path, mode: file.mode, contentBase64: Buffer.from(file.content).toString("base64") })),
  };

  let plan: FactoryGitHubPublicationPlan;
  try { plan = assertFactoryGitHubPublicationRequest(publication); }
  catch (error) {
    if (error instanceof FactoryGitHubError) throw new ReferenceCodeFreezeError("reference_code_candidate_invalid", error.code);
    throw error;
  }

  return Object.freeze({
    schemaVersion: REFERENCE_CODE_FREEZE_SCHEMA_VERSION,
    candidateGeneration: input.candidateGeneration,
    baseSha: snapshot.baseSha,
    treeSha,
    commitSha,
    filesDigest: referenceCodeFilesDigest(sorted),
    changedPaths,
    publication,
    plan,
  });
}
