#!/usr/bin/env bun
// test-entities-fixture — minimal entrypoint.
//
// The host's `installFromLocal` requires an `entrypoint` even when the
// extension has no `tools[]`. For this fixture, the entrypoint is a
// stub that never actually runs: all the extension's tools are
// auto-generated by the SDK from the `entities` declaration in
// `ezcorp.config.ts` and routed to the SDK handler BEFORE reaching
// any subprocess. If the dispatcher ever tried to spawn this fixture,
// `entities-dispatcher.test.ts` and `entities-e2e.test.ts` would
// surface the regression — those tests assert that the entity tool
// dispatch never touches the subprocess.

if (import.meta.main) {
  // The host would only ever exec this if a tool not auto-generated
  // by the SDK landed on the manifest. The fixture deliberately
  // declares none — getting here means a routing regression.
  throw new Error(
    "test-entities-fixture has no subprocess-served tools — entrypoint should never execute",
  );
}
