import { test, expect } from "../fixtures/hydration.js";
import { extensionClient, buildWorkspace, requestRelease, type CreatedWorkspace } from "../fixtures/extension-v4";
import type { InstallationState, LifecycleOperation, WorkspaceRecord } from "../../../src/extensions/v4/types";

test("external harness builds and invokes real code; failed updates retain the approved release", async ({ request, baseURL }) => {
  test.setTimeout(300000);
  const { client } = await extensionClient(request, baseURL!);
  const restricted = (await extensionClient(request, baseURL!, ["read", "chat"])).client;
  await expect(restricted.extensionControl("extensions_workspace", { action: "create", name: "denied" })).rejects.toMatchObject({ status: 403 });
  const name = `harness-${Date.now().toString(36)}`;
  const created = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "create", name });
  const state = await buildWorkspace(client, created);
  const approval = await requestRelease(client, state);
  const approved = await request.post(`/api/extensions/releases/${created.installation.id}/approve`, { data: { approvalId: approval.id, decision: true } });
  expect(approved.status(), await approved.text()).toBe(200);
  await client.extensionControl("extensions_release", { installationId: created.installation.id, action: "activate", approvalId: approval.id, idempotencyKey: crypto.randomUUID() });
  const seeded = await request.post("/api/__test/seed", { data: { title: "v4 harness invocation" } });
  expect(seeded.status(), await seeded.text()).toBe(201);
  const { conversationId } = await seeded.json();
  expect((await client.wireExtensions(conversationId, [name])).wired).toEqual([name]);
  const marker = `actual-isolated-result-${crypto.randomUUID()}`;
  const result = await client.invokeExtensionTool(conversationId, name, "echo", { text: marker });
  expect(result.success, JSON.stringify(result)).toBe(true);
  expect(JSON.stringify(result.output)).toContain(marker);
  await expect(restricted.invokeExtensionTool(conversationId, name, "echo", { text: marker })).rejects.toMatchObject({ status: 403 });
  const changed = await client.extensionControl<WorkspaceRecord>("extensions_workspace", { action: "edit", installationId: created.installation.id, workspaceId: created.workspace.id, expectedRevision: created.workspace.revision, writes: { "src/echo.test.ts": 'import { test, expect } from "bun:test"; test("must fail", () => expect(false).toBe(true));' } });
  await expect(client.extensionControl("extensions_workspace", { action: "edit", installationId: created.installation.id, workspaceId: created.workspace.id, expectedRevision: created.workspace.revision, writes: { "README.md": "stale" } })).rejects.toMatchObject({ status: 409 });
  const operation = await client.extensionControl<LifecycleOperation>("extensions_build", { installationId: created.installation.id, workspaceId: changed.id, expectedRevision: changed.revision, idempotencyKey: crypto.randomUUID() });
  await expect.poll(async () => {
    const failed = await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id, operationId: operation.id, waitMs: 1000 });
    return failed.operations[operation.id]!.state;
  }, { timeout: 180000, intervals: [1000] }).toBe("failed");
  const retained = await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id });
  expect(retained.installation.activeReleaseId).toBe(Object.values(state.releases)[0]!.id);
  expect(Object.keys(retained.releases)).toHaveLength(1);
  expect((await client.invokeExtensionTool(conversationId, name, "echo", { text: marker })).success).toBe(true);
  await client.extensionControl("extensions_release", { action: "disable", installationId: created.installation.id });
  await expect(client.invokeExtensionTool(conversationId, name, "echo", { text: marker })).rejects.toBeDefined();
  await client.extensionControl("extensions_release", { action: "uninstall", installationId: created.installation.id });
  expect((await client.listExtensions()).some((extension) => extension.name === name)).toBe(false);
});
