import { test, expect } from "../fixtures/hydration.js";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execFileSync } from "node:child_process";
import { captureEvidence } from "../fixtures/evidence";
import { extensionClient, buildWorkspace, requestRelease, type CreatedWorkspace } from "../fixtures/extension-v4";
import type { WorkspaceRecord } from "../../../src/extensions/v4/types";

test("real project binding, isolated Git read, host review and revoke @evidence", async ({ page, request, baseURL }, testInfo) => {
  test.setTimeout(300000);
  const root = await mkdtemp(join(tmpdir(), "ez-project-browser-"));
  const git = (...args: string[]) => execFileSync("git", ["-c", "core.hooksPath=/dev/null", "-C", root, ...args], { env: { ...process.env, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_GLOBAL: "/dev/null", GIT_AUTHOR_NAME: "Fixture", GIT_AUTHOR_EMAIL: "fixture@example.invalid", GIT_COMMITTER_NAME: "Fixture", GIT_COMMITTER_EMAIL: "fixture@example.invalid" }, encoding: "utf8" }).trim();
  git("init"); git("commit", "--allow-empty", "-m", "Actual project broker commit"); git("remote", "add", "origin", "https://github.com/owner/repository.git");
  const head = git("rev-parse", "HEAD");
  const { client, key } = await extensionClient(request, baseURL!);
  let installationId: string | undefined;
  try {
    const projectResponse = await request.post("/api/projects", { data: { name: "Project authority fixture", path: root } });
    expect(projectResponse.status(), await projectResponse.text()).toBe(201);
    const project = await projectResponse.json();
    const conversationResponse = await request.post("/api/conversations", { data: { projectId: project.id, title: "Project broker verification" } });
    expect(conversationResponse.status(), await conversationResponse.text()).toBe(201);
    const conversation = await conversationResponse.json();
    const name = `project-review-${Date.now().toString(36)}`;
    const created = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "create", name });
    installationId = created.installation.id;
    const manifest = { schemaVersion: 4, name, version: "1.0.0", description: "Real project authority fixture", author: { name: "E2E" }, permissions: { shell: true, network: ["api.github.com"] }, tools: [{ name: "echo", description: "Read scoped project metadata", inputSchema: { type: "object", properties: { text: { type: "string" } }, required: ["text"], additionalProperties: false }, outputSchema: { type: "object", properties: { text: { type: "string" } }, required: ["text"], additionalProperties: false } }], smokeTest: { tool: "echo", input: { text: "hello" }, expect: { textIncludes: "hello" } } };
    const source = `import {defineExtension,serve} from '@ezcorp/sdk/v4';await serve(defineExtension({manifest:${JSON.stringify(manifest)},tools:{echo:async(input,ctx)=>{const text=(input as {text:string}).text;try{if(text==='head')return{text:JSON.stringify(await ctx.call('ezcorp/project.gitHead',{}))};if(text==='binding')return{text:JSON.stringify(await ctx.call('ezcorp/project.pullRequest',{action:'files',number:42}))};return{text};}catch(error){return{text:error instanceof Error?error.message:String(error)}}}}}));`;
    created.workspace = await client.extensionControl<WorkspaceRecord>("extensions_workspace", { action: "edit", installationId, workspaceId: created.workspace.id, expectedRevision: created.workspace.revision, writes: { "extension.ts": source } });
    const state = await buildWorkspace(client, created);
    const approval = await requestRelease(client, state);
    expect((await request.post(`/api/extensions/releases/${installationId}/approve`, { data: { approvalId: approval.id, decision: true } })).status()).toBe(200);
    await client.extensionControl("extensions_release", { action: "activate", installationId, approvalId: approval.id, idempotencyKey: crypto.randomUUID() });
    await page.goto(created.openUrl);
    await page.getByLabel("Project", { exact: true }).selectOption(project.id);
    await page.getByLabel("Approved write paths").fill("README.md, docs/");
    const bind = page.getByRole("button", { name: "Approve project access", exact: true });
    await expect(bind).toBeDisabled();
    await page.getByRole("checkbox", { name: "I reviewed this project's access and exact release." }).check();
    await bind.click();
    await expect(page.getByRole("status")).toContainText("Project access approved");
    const denied = await fetch(`${baseURL}/api/extensions/releases/${installationId}/project`, { method: "POST", headers: { authorization: `Bearer ${key}`, "content-type": "application/json" }, body: JSON.stringify({ projectId: project.id, releaseId: Object.values(state.releases)[0]!.id, generation: 1 }) });
    expect(denied.status).toBe(403);
    await client.wireExtensions(conversation.id, [name]);
    const result = await client.invokeExtensionTool(conversation.id, name, "echo", { text: "head" });
    expect(result.success, JSON.stringify(result)).toBe(true);
    expect(JSON.stringify(result.output)).toContain(head);
    const seeded = await request.post("/api/__test/project-proposal", { data: { installationId } });
    expect(seeded.status(), await seeded.text()).toBe(201);
    const proposal = await seeded.json();
    expect(proposal.controlledFixture).toBe(true);
    await page.goto(proposal.reviewUrl);
    await expect(page.getByRole("heading", { name: "Review project changes" })).toBeVisible();
    await expect(page.getByText("docs/controlled-fixture.md")).toBeVisible();
    const reject = page.getByRole("button", { name: "Reject without changes", exact: true });
    await expect(reject).toBeDisabled();
    await captureEvidence(page, testInfo, "extension-project-review-desktop");
    await page.setViewportSize({ width: 390, height: 844 });
    await reject.scrollIntoViewIfNeeded();
    await captureEvidence(page, testInfo, "extension-project-review-mobile");
    await page.getByRole("checkbox").check();
    await reject.click();
    await expect(page.getByText("This decision is final.", { exact: false })).toBeVisible();
    await page.goto(created.openUrl);
    await page.getByRole("button", { name: "Revoke project access", exact: true }).click();
    await expect(page.getByRole("status")).toContainText("Project access revoked");
    const revoked = await client.invokeExtensionTool(conversation.id, name, "echo", { text: "binding" });
    expect(JSON.stringify(revoked.output)).toContain("Host capability denied or failed");
    expect((await request.get(proposal.reviewUrl)).status()).toBe(403);
  } finally {
    if (installationId) await client.extensionControl("extensions_release", { action: "uninstall", installationId });
    await rm(root, { recursive: true, force: true });
  }
});
