import { readFile } from "node:fs/promises";
import { test, expect } from "../fixtures/hydration.js";
import { captureEvidence } from "../fixtures/evidence";
import { extensionClient, buildWorkspace, type CreatedWorkspace } from "../fixtures/extension-v4";
import type { WorkspaceFiles, WorkspaceRecord } from "@ezcorp/extension-contract";

test("binary upload, download, isolated build and immutable fork preserve bytes and executable mode @evidence", async ({ page, request, baseURL }, testInfo) => {
  test.setTimeout(300000);
  const { client } = await extensionClient(request, baseURL!);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  const created = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "create", name: `assets-${Date.now().toString(36)}` });
  await page.goto(created.openUrl);
  await expect(page.getByRole("heading", { name: "Extension workspace", exact: true })).toBeVisible();
  expect(errors).toEqual([]);
  const png = Buffer.alloc(600 * 1024);
  Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=", "base64").copy(png);
  await page.getByLabel("Add a file", { exact: true }).fill("assets/pixel.png");
  await page.getByLabel("Upload a file", { exact: true }).setInputFiles({ name: "pixel.png", mimeType: "image/png", buffer: png });
  await expect(page.getByTestId("binary-asset")).toContainText("614400 bytes");
  await expect(page.getByRole("textbox", { name: "Source: assets/pixel.png" })).toHaveCount(0);
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download asset", exact: true }).click();
  const download = await downloaded;
  expect(download.suggestedFilename()).toBe("pixel.png");
  expect(await readFile((await download.path())!)).toEqual(png);
  await page.getByLabel("Add a file", { exact: true }).fill("bin/helper");
  await page.getByLabel("Executable asset (runner only)").check();
  const helper = Buffer.from("#!/bin/sh\nprintf isolated-asset\n");
  await page.getByLabel("Upload a file", { exact: true }).setInputFiles({ name: "helper", mimeType: "application/octet-stream", buffer: helper });
  await expect(page.getByTestId("binary-asset")).toContainText("Executable in runner");
  await captureEvidence(page, testInfo, "extension-binary-assets-desktop", { fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  const fileButtons = page.getByRole("complementary", { name: "Workspace files" }).getByRole("button");
  for (const button of await fileButtons.all()) expect((await button.boundingBox())!.height).toBeGreaterThan(30);
  await captureEvidence(page, testInfo, "extension-binary-assets-mobile", { fullPage: true });
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.getByRole("button", { name: "Save revision", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved revision");
  const source = await client.extensionControl<{ workspace: WorkspaceRecord; files: WorkspaceFiles }>("extensions_workspace", { action: "read", installationId: created.installation.id, workspaceId: created.workspace.id });
  expect(source.files["assets/pixel.png"]).toEqual({ encoding: "base64", data: png.toString("base64"), executable: false });
  expect(source.files["bin/helper"]).toEqual({ encoding: "base64", data: helper.toString("base64"), executable: true });
  created.workspace = source.workspace;
  const state = await buildWorkspace(client, created);
  expect(state.installation.activeReleaseId).toBeNull();
  const fork = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "fork", installationId: created.installation.id, releaseId: Object.values(state.releases)[0]!.id });
  const reopened = await client.extensionControl<{ files: WorkspaceFiles }>("extensions_workspace", { action: "read", installationId: created.installation.id, workspaceId: fork.workspace.id });
  expect(reopened.files).toEqual(source.files);
  await page.getByRole("button", { name: "Remove selected file", exact: true }).click();
  await page.getByRole("button", { name: "Save revision", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved revision");
  const edited = await client.extensionControl<{ files: WorkspaceFiles }>("extensions_workspace", { action: "read", installationId: created.installation.id, workspaceId: created.workspace.id });
  expect(edited.files["bin/helper"]).toBeUndefined();
  expect(reopened.files["bin/helper"]).toEqual(source.files["bin/helper"]);
  expect(errors.filter(message => /Content Security Policy|unsafe-eval|EvalError/.test(message))).toEqual([]);
});
