import { test, expect } from "../fixtures/hydration.js";
import { captureEvidence } from "../fixtures/evidence";
import { extensionClient, buildWorkspace, waitForExtensionBuild, requestRelease, type CreatedWorkspace } from "../fixtures/extension-v4";
import type { InstallationState, LifecycleOperation, WorkspaceRecord } from "../../../src/extensions/v4/types";

test("member imports verified marketplace source into their own installation and opens review @evidence", async ({ browser, request, baseURL }, testInfo) => {
  test.setTimeout(360000);
  const email = `source-import-${Date.now()}@example.test`;
  const invitation = await request.post("/api/auth/invite", { data: { email, role: "member" } });
  expect(invitation.status(), await invitation.text()).toBe(201);
  const { invite } = await invitation.json();
  const context = await browser.newContext({ baseURL, viewport: { width: 1280, height: 900 } });
  let cleanup: (() => Promise<unknown>) | undefined;
  try {
    const accepted = await context.request.post(`/api/auth/invite/${invite.token}`, { data: { name: "Source Import Member", email, password: "Source-Import-E2e-9x!" } });
    expect(accepted.status(), await accepted.text()).toBe(201);
    const profile = await context.request.get("/api/auth/me");
    const { user } = await profile.json();
    expect(user.role).toBe("member");
    const onboarded = await context.request.post("/api/onboarding/complete");
    expect(onboarded.status(), await onboarded.text()).toBe(204);
    const { client } = await extensionClient(context.request, baseURL!);
    const created = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "create", name: `source-import-${Date.now().toString(36)}` });
    cleanup = () => client.extensionControl("extensions_release", { action: "uninstall", installationId: created.installation.id, idempotencyKey: crypto.randomUUID() });
    const initial = await buildWorkspace(client, created);
    const original = Object.values(initial.releases)[0]!;
    const seeded = await context.request.post("/api/__test/marketplace-release", { data: { installationId: created.installation.id, releaseId: original.id } });
    expect(seeded.status(), await seeded.text()).toBe(201);
    const { versionId } = await seeded.json();
    const page = await context.newPage();
    await page.goto(`/extensions/import-source?installation=${created.installation.id}`);
    await expect(page.getByRole("heading", { name: "Import extension source", exact: true })).toBeVisible();
    expect(await page.getByLabel("Installation").inputValue()).toBe(created.installation.id);
    await expect(page.getByRole("option", { name: "Create a new installation" })).toHaveCount(0);
    await page.getByLabel("Source type").selectOption("marketplace");
    await page.getByLabel("Marketplace version ID").fill(versionId);
    await captureEvidence(page, testInfo, "extension-source-import-form");
    await page.setViewportSize({ width: 390, height: 844 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await captureEvidence(page, testInfo, "extension-source-import-mobile", { fullPage: true });
    await page.setViewportSize({ width: 1280, height: 900 });
    const importedResponse = page.waitForResponse((response) => response.url().endsWith("/api/extensions/import-source") && response.request().method() === "POST");
    await page.getByRole("button", { name: "Import and build candidate", exact: true }).click();
    const imported = await importedResponse;
    expect(imported.status(), await imported.text()).toBe(200);
    const staged = await imported.json() as { installation: InstallationState["installation"]; workspace: WorkspaceRecord; operation: LifecycleOperation };
    expect(staged.installation.id).toBe(created.installation.id);
    expect(staged.installation.ownerId).toBe(user.id);
    await expect(page).toHaveURL(new RegExp(`/extensions/author\\?installation=${created.installation.id}&workspace=${staged.workspace.id}`));
    const state = await waitForExtensionBuild(client, created.installation.id, staged.operation.id);
    expect(state.installation).toMatchObject({ ownerId: user.id, enabled: false, activeReleaseId: null, grants: [] });
    expect(state.approvals).toEqual({});
    expect(Object.values(state.releases)).toHaveLength(2);
    const release = state.releases[state.operations[staged.operation.id]!.releaseId!]!;
    expect(release.manifest.name).toBe(original.manifest.name);
    const approval = await requestRelease(client, state, release.id);
    await page.reload();
    await expect(page.getByRole("button", { name: "Approve exact release", exact: true })).toBeDisabled();
    await expect(page.getByText("An administrator must review this release in a human session. API keys cannot approve.")).toBeVisible();
    const forbidden = await context.request.post(`/api/extensions/releases/${created.installation.id}/approve`, { data: { approvalId: approval.id, decision: true } });
    expect(forbidden.status()).toBe(403);
    await captureEvidence(page, testInfo, "extension-source-import-review");
    expect((await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id })).installation.activeReleaseId).toBeNull();
  } finally { await cleanup?.(); await context.close(); }
});
