import { test, expect } from "../fixtures/hydration.js";
import { captureEvidence } from "../fixtures/evidence";
import { extensionClient, buildWorkspace, requestRelease, type CreatedWorkspace } from "../fixtures/extension-v4";
import type { InstallationState } from "../../../src/extensions/v4/types";

test("nested workspace → isolated build → exact human approval → activation @evidence", async ({ page, request, baseURL }, testInfo) => {
  test.setTimeout(300000);
  const { client, key } = await extensionClient(request, baseURL!);
  const created = await client.extensionControl<CreatedWorkspace>("extensions_workspace", { action: "create", name: `review-${Date.now().toString(36)}` });
  await page.goto(created.openUrl);
  await expect(page.getByRole("heading", { name: "Extension workspace", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "src/echo.ts", exact: true }).click();
  await expect(page.getByRole("textbox", { name: "Source: src/echo.ts", exact: true })).toHaveValue(/export function echo/);
  await page.getByLabel("Add a file", { exact: true }).fill("docs/nested/review.md");
  await page.getByRole("button", { name: "Add file", exact: true }).click();
  await page.getByRole("textbox", { name: "Source: docs/nested/review.md", exact: true }).fill("Reviewed source stays in a revision.");
  await page.getByRole("button", { name: "Save revision", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Saved revision");
  const before = await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id });
  created.workspace = before.workspaces[created.workspace.id]!;
  const state = await buildWorkspace(client, created);
  const approval = await requestRelease(client, state);
  const forbidden = await fetch(`${baseURL}/api/extensions/releases/${created.installation.id}/approve`, { method: "POST", headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" }, body: JSON.stringify({ approvalId: approval.id, decision: true }) });
  expect(forbidden.status).toBe(403);
  await page.reload();
  const approve = page.getByRole("button", { name: "Approve exact release", exact: true });
  await expect(approve).toBeDisabled();
  await page.getByText("Permissions and test evidence", { exact: true }).click();
  await approve.scrollIntoViewIfNeeded();
  await captureEvidence(page, testInfo, "extension-release-desktop", { fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.locator("body")).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await approve.scrollIntoViewIfNeeded();
  await captureEvidence(page, testInfo, "extension-release-mobile", { fullPage: true });
  await page.getByLabel("I reviewed this release and its permissions.").check();
  await approve.click();
  await page.getByRole("button", { name: "Activate approved release", exact: true }).click();
  await expect(page.getByRole("button", { name: "Disable installation", exact: true })).toBeEnabled();
  const active = await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id });
  expect(active.installation.enabled).toBe(true);
  expect(active.installation.activeReleaseId).toBe(Object.values(state.releases)[0]!.id);
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.goto(`/extensions/${created.installation.id}`);
  await expect(page.getByTestId("review-extension-release")).toBeVisible();
  await page.getByTestId("release-permissions").scrollIntoViewIfNeeded();
  await captureEvidence(page, testInfo, "extension-detail-release-permissions", { fullPage: true });
  await page.getByTestId("review-extension-release").click();
  await expect(page).toHaveURL(new RegExp(`installation=${created.installation.id}`));
  await page.getByRole("button", { name: "Disable installation", exact: true }).click();
  await expect(page.getByRole("button", { name: "Disable installation", exact: true })).toBeDisabled();
  await page.goto(`/extensions/${created.installation.id}`);
  await page.getByRole("button", { name: "Uninstall", exact: true }).click();
  const dialog = page.getByTestId("uninstall-dialog");
  await expect(dialog).toContainText("release history, settings, secrets, stored data and files are kept");
  await expect(dialog.getByRole("radio")).toHaveCount(0);
  await captureEvidence(page, testInfo, "extension-uninstall-retains-data");
  await dialog.getByTestId("uninstall-confirm").click();
  await expect(page).toHaveURL(/\/extensions$/);
  const removed = await client.extensionControl<InstallationState>("extensions_inspect", { installationId: created.installation.id });
  expect(removed.installation.uninstalled).toBe(true);
  expect(removed.releases).toEqual(active.releases);
});
