/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: d5baf39550f6fa2ccb22d43c2b9cceca)
interface __BaseEnv_Env {
	APP_ID?: string;
	APP_CLIENT_ID?: string;
	APP_SLUG?: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../../src/integrations/github-app-directory/worker");
	}
	interface ProductionEnv {
		APP_ID: string;
		APP_CLIENT_ID: string;
		APP_SLUG: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ID" | "APP_CLIENT_ID" | "APP_SLUG">> {}
}
