#!/usr/bin/env bash
# Builds the pinned PyArrow runner image for `reference.data.v1` FROM THE LOCK.
#
# The image is the C10 release lock's Python runner: its base is pinned by
# registry digest, its dependency closure is generated from the committed
# `src/factory/runner/python/uv.lock` and installed hash-verified, and nothing
# is resolved at build time that the lock does not already name.
#
# The tag is derived from the lock and the Containerfile, so a changed closure
# is a different image rather than a silently replaced one.
#
# The build reproduces on the same toolchain: every build is a clean rebuild
# with all timestamps fixed, so on one Podman version the same lock and
# Containerfile give the same manifest digest. Across Podman versions, layer
# tar ordering and compression are not proven. The script compares what it
# built with the committed pin; on any difference it removes what it built and
# fails. Pass --repin only when the lock or the Containerfile changed on
# purpose; it records the new pin instead of failing.
#
# Usage: bash scripts/build-factory-data-image.sh [--print-tag | --repin]
set -uo pipefail

MODE=check
case "${1:-}" in
  "") ;;
  --print-tag) MODE=print-tag ;;
  --repin) MODE=repin ;;
  *) echo "factory data image: unknown argument '$1' (expected --print-tag or --repin)" >&2; exit 2 ;;
esac

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
PROJECT_REL="src/factory/runner/python"
CONTEXT="$REPO_ROOT/src/factory/reference-data/image"
LOCK="$REPO_ROOT/$PROJECT_REL/uv.lock"

fail() { echo "factory data image: $*" >&2; exit 1; }

[ -f "$LOCK" ] || fail "missing $PROJECT_REL/uv.lock"
[ -f "$CONTEXT/Containerfile" ] || fail "missing image context"

if command -v uv >/dev/null 2>&1; then uv_exec() { uv "$@"; }
elif command -v nix-shell >/dev/null 2>&1; then uv_exec() { nix-shell -p uv --run "uv $(printf '%q ' "$@")"; }
else fail "no 'uv' available; the closure cannot be generated without the lock resolver"; fi

cd "$REPO_ROOT" || fail "cannot enter repository root"
uv_exec export --locked --no-dev --no-emit-project --format requirements.txt --project "$PROJECT_REL" \
  > "$CONTEXT/locked-requirements.txt" 2>/dev/null \
  || fail "'uv export --locked' failed: the lock does not reproduce"
[ -s "$CONTEXT/locked-requirements.txt" ] || fail "'uv export --locked' wrote nothing"
grep -q '^pyarrow==' "$CONTEXT/locked-requirements.txt" || fail "the exported closure does not contain pyarrow"

# Hashed as a byte stream, never through a command substitution: `$(cat ...)`
# strips trailing newlines, and the tag must be reproducible from the same two
# files by src/factory/reference-data/guest.ts.
TAG=$(cat "$LOCK" "$CONTEXT/Containerfile" | sha256sum | cut -c1-32)
IMAGE="localhost/ezcorp-factory-python-data:$TAG"
# The build lands under its own candidate tag. Only a build that matches the
# pin (or one recorded with --repin) gets the real tag, so a failed check can
# drop exactly what it built and never moves or removes the pinned image, even
# when the inputs are unchanged and the tags would be equal.
CANDIDATE="localhost/ezcorp-factory-python-data:candidate-$TAG"
discard() { podman rmi "$CANDIDATE" >/dev/null 2>&1; }

if [ "$MODE" = print-tag ]; then echo "$IMAGE"; exit 0; fi

# Reproducibility levers, each needed:
# - `--no-cache`: a build never reuses a cached layer, so a matching digest
#   proves the build reproduces rather than that the cache was warm.
# - `--timestamp 0`: the image's created time, its history, and every file in
#   every new layer carry the epoch instead of the build time.
# - `--identity-label=false`: no build-tool version label in the config, so
#   the label is not one more input that differs between toolchains.
# The Containerfile keeps build-stamped bytes (bytecode, caches) out of the layer.
echo "→ building $IMAGE" >&2
podman build --pull=never --no-cache --timestamp 0 --identity-label=false \
  --tag "$CANDIDATE" --file "$CONTEXT/Containerfile" "$CONTEXT" >&2 \
  || { discard; fail "podman build failed"; }

# The RELEASE LOCK. The runner refuses any image reference that is not an
# immutable digest, so the build records the manifest digest it produced and the
# repository carries it. On the same toolchain a rebuild from the same lock and
# Containerfile must give the committed digest. The runner's build lane
# also re-reads the closure from a live guest and compares it with the
# declaration before it will seal an artifact.
DIGEST=$(podman image inspect "$CANDIDATE" --format '{{.Digest}}' 2>/dev/null) || { discard; fail "the built image is not inspectable"; }
case "$DIGEST" in
  sha256:*) ;;
  *) discard; fail "the built image has no manifest digest: $DIGEST" ;;
esac
LOCK_DIGEST="sha256:$(sha256sum "$LOCK" | cut -d' ' -f1)"
BASE=$(grep '^FROM ' "$CONTEXT/Containerfile" | head -1 | cut -d' ' -f2)

PIN=$(cat <<JSON
{
  "note": "Generated by scripts/build-factory-data-image.sh. The release lock for reference.data.v1's Python runner image. Do not hand-edit: rebuild instead.",
  "repository": "localhost/ezcorp-factory-python-data",
  "tag": "$TAG",
  "image": "localhost/ezcorp-factory-python-data@$DIGEST",
  "base": "$BASE",
  "lockDigest": "$LOCK_DIGEST"
}
JSON
)

if [ -f "$CONTEXT/pinned.json" ] && [ "$PIN" = "$(cat "$CONTEXT/pinned.json")" ]; then
  echo "→ reproduced the committed pin in $CONTEXT/pinned.json" >&2
elif [ "$MODE" = repin ]; then
  printf '%s\n' "$PIN" > "$CONTEXT/pinned.json"
  echo "→ recorded $CONTEXT/pinned.json" >&2
else
  # A failed check leaves nothing behind: removing the candidate tag deletes
  # the image unless another tag still names the same image.
  discard
  COMMITTED=$(grep -o '"image": "[^"]*"' "$CONTEXT/pinned.json" 2>/dev/null | cut -d'"' -f4)
  fail "the build did not reproduce the committed pin: built localhost/ezcorp-factory-python-data@$DIGEST, pinned ${COMMITTED:-nothing}. The built image was removed. Pass --repin only if the lock or the Containerfile changed on purpose."
fi
podman tag "$CANDIDATE" "$IMAGE" || { discard; fail "could not tag the built image as $IMAGE"; }
discard
echo "localhost/ezcorp-factory-python-data@$DIGEST"
