/**
 * The reference image pack's content lock.
 *
 * One committed document pins everything a variant's bytes can depend on: the
 * model repository revision and every weight digest, the container image the
 * guest runs in, the interpreter, the generation settings C10 fixes, the PNG
 * normalization, the OCR configuration and its threshold, and the semantic
 * evaluation configuration. Nothing in the pack resolves any of these at
 * execution time, so two runs that disagree disagree about the hardware rather
 * than about what was asked.
 *
 * `referenceImageLockDigest` is the value a recipe and an evidence record carry.
 * It covers the whole document, so changing a seed, a threshold, or a weight
 * digest produces a different lock and therefore a different decision.
 */
import { createHash } from "node:crypto";

import lockDocument from "./sdxl-lock.json" with { type: "json" };
import {
  assertReferenceImageModelLock,
  IMAGE,
  invalid,
  ReferenceImageLockError,
  referenceImageModelDocument,
  sdxlClosureDirectoryFor,
  type ReferenceImageModelLock,
} from "./model-lock.ts";

export { assertReferenceImageModelLock, ReferenceImageLockError, referenceImageModelDocument, sdxlClosureDirectoryFor };
export type { ReferenceImageModelFile, ReferenceImageModelLock } from "./model-lock.ts";

export const REFERENCE_IMAGE_LOCK_SCHEMA_VERSION = "factory.reference-image-lock.v1";

export interface ReferenceImageRuntimeLock {
  /** The registry-pinned base the guest image is built from. */
  readonly baseImage: string;
  /** The built guest image, by its own registry digest. This is the closure pin. */
  readonly guestImage: string;
  /** The interpreter the built image ships, which is not the repository's host pin. */
  readonly pythonVersion: string;
  /**
   * Every distribution the launched interpreter reports, as `name==version`.
   *
   * Recorded rather than assumed. The shared Python runner compares this list
   * with what the guest actually has and refuses the build on any difference,
   * so a rebuilt image that gained a transitive dependency fails here instead
   * of changing what a variant was generated by.
   */
  readonly distributions: readonly string[];
  readonly resourceClass: string;
  readonly modelDirectory: string;
}

/** Exactly the C10 settings. Every field is a fixed input, not a default. */
export interface ReferenceImageGenerationLock {
  readonly seeds: readonly number[];
  readonly inferenceSteps: number;
  readonly guidanceScale: number;
  readonly width: number;
  readonly height: number;
  readonly dtype: string;
  readonly scheduler: string;
  readonly device: string;
  readonly selector: string;
}

export interface ReferenceImageNormalizationLock {
  readonly format: string;
  readonly colorMode: string;
  readonly bitDepth: number;
  readonly compressLevel: number;
  readonly stripAncillaryChunks: boolean;
  /** The only chunk types a normalized variant may contain. */
  readonly allowedChunks: readonly string[];
  readonly maximumBytes: number;
}

export interface ReferenceImageOcrLock {
  readonly engine: string;
  readonly language: string;
  readonly pageSegmentationMode: number;
  readonly engineMode: number;
  /** A word at or above this confidence counts as recognized text. */
  readonly minimumWordConfidence: number;
}

export interface ReferenceImageEvaluationLock {
  readonly model: string;
  readonly fields: readonly string[];
  readonly evaluations: number;
  readonly minimumPasses: number;
  readonly requireAllDecisive: boolean;
  readonly maxOutputTokens: number;
  readonly temperature: number;
}

export interface ReferenceImageLock {
  readonly schemaVersion: typeof REFERENCE_IMAGE_LOCK_SCHEMA_VERSION;
  readonly definitionId: string;
  readonly model: ReferenceImageModelLock;
  readonly runtime: ReferenceImageRuntimeLock;
  readonly generation: ReferenceImageGenerationLock;
  readonly normalization: ReferenceImageNormalizationLock;
  readonly ocr: ReferenceImageOcrLock;
  readonly evaluation: ReferenceImageEvaluationLock;
}

/** Stable key order, so the digest measures content rather than authoring order. */
function canonical(value: unknown): string {
  if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null";
  if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`;
  const entries = Object.entries(value as Record<string, unknown>).filter(([, item]) => item !== undefined);
  entries.sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0));
  return `{${entries.map(([key, item]) => `${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;
}

/**
 * The guest closure: both images by digest, the interpreter, the distributions
 * the launched interpreter reports, and where the weights are mounted.
 */
function assertRuntimeLock(value: unknown): void {
  const runtime = value as Record<string, unknown> | undefined;
  if (typeof runtime?.baseImage !== "string" || !IMAGE.test(runtime.baseImage)) invalid("The runtime base image must be pinned by registry digest");
  if (typeof runtime.guestImage !== "string" || !IMAGE.test(runtime.guestImage)) invalid("The runtime guest image must be pinned by registry digest");
  if (!Array.isArray(runtime.distributions) || runtime.distributions.length === 0) invalid("The runtime must record the guest's importable distributions");
  let distribution = "";
  for (const entry of runtime.distributions as readonly unknown[]) {
    if (typeof entry !== "string" || !/^[^=]+==[^=]+$/.test(entry)) invalid(`Distribution ${String(entry)} must be recorded as name==version`);
    if (entry <= distribution) invalid(`Distributions must be sorted and unique; ${entry} follows ${distribution}`);
    distribution = entry;
  }
  if (typeof runtime.pythonVersion !== "string" || !/^\d+\.\d+\.\d+$/.test(runtime.pythonVersion)) invalid("The runtime must pin an exact interpreter version");
  if (typeof runtime.resourceClass !== "string" || runtime.resourceClass.length === 0) invalid("The runtime must name its resource class");
  if (typeof runtime.modelDirectory !== "string" || !runtime.modelDirectory.startsWith("/")) invalid("The runtime must name an absolute model directory");
}

/** Exactly the C10 generation settings, every one a fixed input. */
function assertGenerationLock(value: unknown): void {
  const generation = value as Record<string, unknown> | undefined;
  if (!Array.isArray(generation?.seeds) || generation.seeds.length === 0) invalid("The generation lock must record its seeds");
  let seed = -1;
  for (const entry of generation.seeds as readonly unknown[]) {
    if (typeof entry !== "number" || !Number.isSafeInteger(entry) || entry < 0) invalid("Every seed must be a nonnegative integer");
    if (entry <= seed) invalid("Seeds must be recorded in ascending input order without duplicates");
    seed = entry;
  }
  for (const field of ["inferenceSteps", "width", "height"] as const) {
    const item = generation[field];
    if (typeof item !== "number" || !Number.isSafeInteger(item) || item <= 0) invalid(`The generation lock must pin ${field}`);
  }
  if (typeof generation.guidanceScale !== "number" || !Number.isFinite(generation.guidanceScale) || generation.guidanceScale <= 0) invalid("The generation lock must pin its guidance scale");
  for (const field of ["dtype", "scheduler", "device", "selector"] as const) {
    if (typeof generation[field] !== "string" || (generation[field] as string).length === 0) invalid(`The generation lock must pin ${field}`);
  }
}

/** The PNG normalization: one byte layout, and only the chunks it allows. */
function assertNormalizationLock(value: unknown): void {
  const normalization = value as Record<string, unknown> | undefined;
  if (normalization?.format !== "PNG") invalid("The normalization lock must produce PNG");
  if (typeof normalization.colorMode !== "string" || !["RGB", "RGBA"].includes(normalization.colorMode)) invalid("The normalization lock must pin an RGB or RGBA colour mode");
  if (normalization.bitDepth !== 8) invalid("The normalization lock must pin eight-bit samples");
  if (typeof normalization.compressLevel !== "number" || !Number.isSafeInteger(normalization.compressLevel) || normalization.compressLevel < 0 || normalization.compressLevel > 9) invalid("The normalization lock must pin a compression level");
  if (normalization.stripAncillaryChunks !== true) invalid("The normalization lock must strip ancillary chunks");
  if (!Array.isArray(normalization.allowedChunks) || normalization.allowedChunks.length === 0) invalid("The normalization lock must list the chunks it allows");
  for (const chunk of normalization.allowedChunks as readonly unknown[]) {
    if (typeof chunk !== "string" || !/^[A-Za-z]{4}$/.test(chunk)) invalid("Every allowed chunk must be a four-letter type");
  }
  for (const required of ["IHDR", "IDAT", "IEND"]) {
    if (!(normalization.allowedChunks as readonly string[]).includes(required)) invalid(`The normalization lock must allow the critical chunk ${required}`);
  }
  if (typeof normalization.maximumBytes !== "number" || !Number.isSafeInteger(normalization.maximumBytes) || normalization.maximumBytes <= 0) invalid("The normalization lock must pin a maximum size");
}

/** The OCR engine, its language, its modes, and what counts as recognized text. */
function assertOcrLock(value: unknown): void {
  const ocr = value as Record<string, unknown> | undefined;
  if (typeof ocr?.engine !== "string" || ocr.engine.length === 0) invalid("The OCR lock must name its engine");
  if (typeof ocr.language !== "string" || !/^[a-z]{3}$/.test(ocr.language)) invalid("The OCR lock must name a three-letter language");
  for (const field of ["pageSegmentationMode", "engineMode"] as const) {
    const item = ocr[field];
    if (typeof item !== "number" || !Number.isSafeInteger(item) || item < 0) invalid(`The OCR lock must pin ${field}`);
  }
  if (typeof ocr.minimumWordConfidence !== "number" || !Number.isSafeInteger(ocr.minimumWordConfidence) || ocr.minimumWordConfidence < 0 || ocr.minimumWordConfidence > 100) invalid("The OCR lock must pin a word confidence threshold between zero and one hundred");
}

/** The semantic evaluation: its model, its fields, and its quorum. */
function assertEvaluationLock(value: unknown): void {
  const evaluation = value as Record<string, unknown> | undefined;
  if (typeof evaluation?.model !== "string" || evaluation.model.length === 0) invalid("The evaluation lock must name its model");
  if (!Array.isArray(evaluation.fields) || evaluation.fields.length === 0) invalid("The evaluation lock must list its boolean fields");
  let field = "";
  for (const entry of evaluation.fields as readonly unknown[]) {
    if (typeof entry !== "string" || entry.length === 0) invalid("Every evaluation field must be named");
    if (entry === field) invalid("Evaluation fields must be unique");
    field = entry;
  }
  if (new Set(evaluation.fields as readonly string[]).size !== (evaluation.fields as readonly string[]).length) invalid("Evaluation fields must be unique");
  if (typeof evaluation.evaluations !== "number" || !Number.isSafeInteger(evaluation.evaluations) || evaluation.evaluations < 1) invalid("The evaluation lock must count its evaluations");
  if (typeof evaluation.minimumPasses !== "number" || !Number.isSafeInteger(evaluation.minimumPasses) || evaluation.minimumPasses < 1) invalid("The evaluation lock must pin a quorum");
  if (evaluation.minimumPasses > evaluation.evaluations) invalid("The evaluation quorum cannot exceed the number of evaluations");
  if (evaluation.requireAllDecisive !== true) invalid("The evaluation lock must require every evaluation to be decisive");
  if (typeof evaluation.maxOutputTokens !== "number" || !Number.isSafeInteger(evaluation.maxOutputTokens) || evaluation.maxOutputTokens <= 0) invalid("The evaluation lock must pin an output ceiling");
  if (typeof evaluation.temperature !== "number" || !Number.isFinite(evaluation.temperature) || evaluation.temperature < 0) invalid("The evaluation lock must pin a temperature");
}

/**
 * Accepts only a lock that pins every field this pack reads.
 *
 * The checks are deliberately about bindings rather than shape: a revision that
 * is not a commit, an unpinned image, an out-of-order or duplicated file list,
 * a quorum larger than the number of evaluations, or a normalization that
 * permits a chunk outside the allowed set would each let an execution-time
 * decision back in.
 *
 * One assertion per locked section, in the order a reader of the document
 * meets them. The order matters to the caller: the first unpinned field is the
 * one reported, so the sections run exactly as they were written inline.
 */
export function assertReferenceImageLock(value: unknown): asserts value is ReferenceImageLock {
  if (typeof value !== "object" || value === null) invalid("The reference image lock must be an object");
  const lock = value as Record<string, unknown>;
  if (lock.schemaVersion !== REFERENCE_IMAGE_LOCK_SCHEMA_VERSION) invalid(`The reference image lock schema must be ${REFERENCE_IMAGE_LOCK_SCHEMA_VERSION}`);
  if (lock.definitionId !== "reference.image.v1") invalid("The reference image lock must name reference.image.v1");

  assertReferenceImageModelLock(lock.model);
  assertRuntimeLock(lock.runtime);
  assertGenerationLock(lock.generation);
  assertNormalizationLock(lock.normalization);
  assertOcrLock(lock.ocr);
  assertEvaluationLock(lock.evaluation);
}

function frozen(value: ReferenceImageLock): ReferenceImageLock {
  return Object.freeze({
    ...value,
    model: Object.freeze({ ...value.model, files: Object.freeze(value.model.files.map(file => Object.freeze({ ...file }))) }),
    runtime: Object.freeze({ ...value.runtime, distributions: Object.freeze([...value.runtime.distributions]) }),
    generation: Object.freeze({ ...value.generation, seeds: Object.freeze([...value.generation.seeds]) }),
    normalization: Object.freeze({ ...value.normalization, allowedChunks: Object.freeze([...value.normalization.allowedChunks]) }),
    ocr: Object.freeze({ ...value.ocr }),
    evaluation: Object.freeze({ ...value.evaluation, fields: Object.freeze([...value.evaluation.fields]) }),
  });
}

/** Parses a candidate lock document. Used for a caller-supplied or fixture lock. */
export function parseReferenceImageLock(value: unknown): ReferenceImageLock {
  assertReferenceImageLock(value);
  return frozen(value);
}

/** The one lock this installation runs. */
export const referenceImageLock: ReferenceImageLock = parseReferenceImageLock(lockDocument);

/** `sha256:` over the whole canonical lock. A recipe and an evidence record carry this. */
export function referenceImageLockDigest(lock: ReferenceImageLock = referenceImageLock): string {
  return `sha256:${createHash("sha256").update(canonical(lock)).digest("hex")}`;
}

/** The resolve URL for one closure file at the pinned revision. */
export function sdxlWeightUrl(path: string, lock: ReferenceImageLock = referenceImageLock): string {
  const file = lock.model.files.find(entry => entry.path === path);
  if (file === undefined) throw new ReferenceImageLockError("reference_image_lock_unknown_file", `The lock does not declare ${path}`);
  return `${lock.model.source}/${lock.model.repository}/resolve/${lock.model.revision}/${file.path}`;
}

/**
 * Where the sealed weight closure lives on this host.
 *
 * The revision is part of the path, so a lock that moves to another revision
 * cannot read the previous one's bytes out of a warm directory.
 */
export function sdxlClosureDirectory(lock: ReferenceImageLock = referenceImageLock): string {
  return sdxlClosureDirectoryFor(lock.model);
}

/** The sorted `name@sha256:` model pins for a Python runner closure. */
export function referenceImageModelPins(lock: ReferenceImageLock = referenceImageLock): readonly string[] {
  return Object.freeze(
    lock.model.files
      .filter(file => file.digest !== undefined)
      .map(file => `${lock.model.repository}/${file.path}@${file.digest as string}`)
      .sort(),
  );
}


