import { defineExtension } from "../../../../src/extensions/sdk/define";

// ── substack-pilot ───────────────────────────────────────────────
//
// User-defined Substack post types with custom system prompts, plus
// AI-summarize-and-draft from URLs.
//
// Phase 7 of the defineEntity SDK port: post-types are now declared as
// an `entities` block (the SDK auto-generates `list_post_types`,
// `get_post_type`, `create_post_type`, `update_post_type`,
// `delete_post_type`). The host renames legacy `post-type:*` storage
// keys to the managed `__entity:post-type:*` namespace on install (see
// `src/extensions/bundled.ts:ensureBundledExtensions` for the mapping).
// Draft creation invokes the upstream substack-mcp via a stdio child
// process that this extension spawns from `lib/substack.ts` (the host
// registry does not auto-launch mcpServers for local-kind extensions —
// see README "Architecture").
//
// Permission contract:
//  - `storage: true`    — entity CRUD via the SDK's managed namespace
//  - `llm.providers`    — per-URL summarization + draft composition
//  - `network: ["*"]`   — fetch arbitrary URLs the user pastes
//  - `shell: true`      — spawn `npx -y substack-mcp@latest`
//
// Substack credentials live in `settings.substack_*` (validated below)
// and are read at tool-invocation time via `ctx.invocationMetadata.settings`
// in `lib/substack.ts`. We do NOT request `permissions.env` for the SUBSTACK_*
// keys: their names end in `_TOKEN`/`_URL`/`_ID`, and `SUBSTACK_SESSION_TOKEN`
// in particular matches the host's `ENV_KEY_LEAK_PATTERN` install-gate
// (`src/extensions/clamp-permissions.ts` → `checkEnvKeyLeakInstallGate`),
// which would refuse install for non-bundled extensions. Settings storage
// is the correct surface anyway — it persists per-user, never touches host
// process env, and is what `lib/substack.ts` actually reads.

export default defineExtension({
  schemaVersion: 2,
  name: "substack-pilot",
  version: "1.0.0",
  description:
    "Manage Substack post types with custom system prompts and AI-summarize-and-draft from URLs.",
  author: { name: "EZCorp" },
  entrypoint: "./index.ts",
  // Phase 7 — the 5 CRUD tools that previously lived here
  // (list/get/create/update/delete_post_type) are now auto-generated by
  // the SDK from the `entities` block below. Only the bespoke,
  // non-CRUD tools remain in this manifest.
  tools: [
    {
      name: "summarize_urls",
      description:
        "Fetch each URL and produce a short structured summary used for drafting. Returns [{url,title,summary}].",
      inputSchema: {
        type: "object",
        properties: {
          urls: { type: "array", items: { type: "string" } },
          maxWordsPerSummary: {
            type: "number",
            description: "Target word count per summary (default 80, max 400)",
          },
        },
        required: ["urls"],
      },
    },
    {
      name: "generate_substack_draft",
      description:
        "End-to-end: pick a post type, summarize the URLs, compose body, and create a Substack draft. Returns draft id + summary.",
      inputSchema: {
        type: "object",
        properties: {
          postTypeSlug: { type: "string" },
          urls: { type: "array", items: { type: "string" } },
          titleOverride: { type: "string" },
          subtitleOverride: { type: "string" },
        },
        required: ["postTypeSlug", "urls"],
      },
    },
  ],
  // Phase 7 — entity declaration replaces lib/post-types.ts (~421 LOC
  // deleted). The SDK auto-generates the 5 CRUD tools from this
  // declaration and surfaces them on /extensions/<id> as an editable
  // table. `seed` populates 3 default post types on first install via
  // {file:...} placeholders that read from this extension's own
  // prompts/*.md files.
  entities: [
    {
      type: "post-type",
      label: "Post Type",
      pluralLabel: "Post Types",
      scope: "user",
      cascadeOnUninstall: false,
      schema: {
        type: "object",
        properties: {
          name: { type: "string", minLength: 1, maxLength: 100 },
          systemPrompt: {
            type: "string",
            minLength: 1,
            maxLength: 100_000,
          },
          cadence: {
            type: "string",
            // Free-form historically; the SDK schema subset accepts
            // an enum OR a plain string. We keep the well-known
            // values as documentation but DON'T enum-gate — users
            // could legitimately want "biweekly" or "quarterly".
            // The host's soft-read flags drift; the UI shows the
            // banner; the LLM can fix in place.
          },
          defaults: {
            type: "object",
            properties: {
              titlePrefix: { type: "string" },
              subtitleTemplate: { type: "string" },
            },
          },
        },
        required: ["name", "systemPrompt"],
        additionalProperties: false,
      },
      preview:
        "Post type '{name}' ({cadence}):\n{systemPrompt}",
      seed: [
        {
          slug: "weekly",
          data: {
            name: "Weekly Roundup",
            systemPrompt: "{file:./prompts/weekly.md}",
            cadence: "weekly",
            defaults: {
              titlePrefix: "This Week: ",
              subtitleTemplate: "{date} • {count} links",
            },
          },
        },
        {
          slug: "monthly",
          data: {
            name: "Monthly Essay",
            systemPrompt: "{file:./prompts/monthly.md}",
            cadence: "monthly",
            defaults: { titlePrefix: "Monthly: " },
          },
        },
        {
          slug: "ad-hoc",
          data: {
            name: "Ad-hoc Post",
            systemPrompt: "{file:./prompts/ad-hoc.md}",
            cadence: "ad-hoc",
          },
        },
      ],
    },
  ],
  skills: [
    {
      name: "substack-author",
      description:
        "How to use substack-pilot tools to draft Substack posts from a named post type plus URLs.",
      files: ["skills/substack-author/SKILL.md"],
    },
  ],
  // mcpServers is declared for documentation. The host registry only
  // auto-launches an mcpServers entry when `kind: "mcp"`; since this
  // extension is a local-kind subprocess extension with its own tools,
  // the actual `create_draft_post` call is performed by lib/substack.ts
  // spawning the upstream substack-mcp process directly. The declaration
  // here remains as a manifest-level record of the external dependency.
  mcpServers: [
    {
      name: "substack-api",
      transport: "stdio",
      command: "npx",
      args: ["-y", "substack-mcp@latest"],
      env: {
        SUBSTACK_PUBLICATION_URL: "${env.SUBSTACK_PUBLICATION_URL}",
        SUBSTACK_SESSION_TOKEN: "${env.SUBSTACK_SESSION_TOKEN}",
        SUBSTACK_USER_ID: "${env.SUBSTACK_USER_ID}",
      },
    },
  ],
  scripts: {
    postinstall: "./scripts/postinstall.ts",
    preuninstall: "./scripts/preuninstall.ts",
  },
  settings: {
    substack_publication_url: {
      type: "text",
      label: "Publication URL",
      description: "e.g. https://yourname.substack.com",
      pattern: "^https?://[^\\s]+$",
    },
    substack_session_token: {
      type: "text",
      label: "Session token",
      description: "From the substack-mcp creator guide (kept locally, never logged).",
      // Presence-only guard — V2 settings schema doesn't expose `minLength`
      // or `required`, so we use a non-empty `pattern` to reject blank
      // pastes up front. Substack rotates this opaquely; we don't know
      // the format, only that an empty token will 401 cryptically.
      pattern: "^.+$",
    },
    substack_user_id: {
      type: "text",
      label: "User ID",
      description: "Your Substack numeric user id.",
      // Numeric id; non-empty digits-only catches whitespace-only pastes
      // without locking us out of future id formats.
      pattern: "^\\d+$",
    },
  },
  // lib/substack.ts lazily imports `@modelcontextprotocol/sdk` to spawn the
  // substack MCP child. Verify-only (host does NOT install it): must exist
  // in the deployment's node_modules (app root package.json). See
  // src/extensions/npm-deps.ts.
  npmDependencies: { "@modelcontextprotocol/sdk": "^1.29.0" },
  permissions: {
    storage: true,
    llm: {
      providers: ["anthropic", "openai"],
      maxCallsPerHour: 120,
      maxCallsPerDay: 600,
      maxTokensPerCall: 2048,
    },
    network: ["*"], // summarize_urls fetches user-pasted URLs
    shell: true, // spawn `npx -y substack-mcp@latest`
    // NOTE: no `env` grant. SUBSTACK_* values come from settings, not
    // host env. See the header comment for the install-gate rationale.
  },
});
