// Manifest validation — mirrors code-quality/index.test.ts. We also
// pipe the config through the host's `validateManifestV2` to catch
// shape drift early (e.g. a stricter validator landing in main).

import { test, expect, describe } from "bun:test";
import manifest from "./ezcorp.config";
import { validateManifestV2 } from "../../../../src/extensions/manifest";

describe("substack-pilot — manifest shape", () => {
  test("required fields are set", () => {
    expect(manifest.schemaVersion).toBe(2);
    expect(manifest.name).toBe("substack-pilot");
    expect(manifest.version).toBe("1.0.0");
    expect(manifest.author.name).toBe("EZCorp");
    expect(manifest.description.length).toBeGreaterThan(0);
  });

  test("entrypoint is the dispatcher", () => {
    expect(manifest.entrypoint).toBe("./index.ts");
  });

  test("declares the two bespoke (non-CRUD) tools by name", () => {
    // Phase 7 — the 5 CRUD tools (list/get/create/update/delete_post_type)
    // are now auto-generated by the SDK from the `entities` block. Only
    // the hand-rolled tools live in manifest.tools[].
    const names = (manifest.tools ?? []).map((t) => t.name);
    expect(names).toEqual(["summarize_urls", "generate_substack_draft"]);
  });

  test("every tool has description + inputSchema", () => {
    for (const t of manifest.tools ?? []) {
      expect(typeof t.description).toBe("string");
      expect(t.description.length).toBeGreaterThan(0);
      expect(t.inputSchema).toBeDefined();
      expect((t.inputSchema as { type: string }).type).toBe("object");
    }
  });

  test("declares the post-type entity (replaces hand-rolled CRUD)", () => {
    // Phase 7 — the SDK auto-generates the 5 CRUD tools from this
    // declaration. The declaration shape is locked by the SDK at
    // `@ezcorp/sdk/entities`; we only spot-check the substack-pilot-
    // specific fields here.
    const entities = (manifest as { entities?: unknown[] }).entities ?? [];
    expect(entities).toHaveLength(1);
    const decl = entities[0] as {
      type: string;
      label: string;
      pluralLabel: string;
      scope: string;
      seed?: Array<{ slug: string }>;
    };
    expect(decl.type).toBe("post-type");
    expect(decl.label).toBe("Post Type");
    expect(decl.pluralLabel).toBe("Post Types");
    expect(decl.scope).toBe("user");
    // The 3 default seeds match the pre-port `lib/post-types.ts`
    // `PRODUCTION_SEEDS` list — install-time default population.
    expect(decl.seed?.map((s) => s.slug).sort()).toEqual([
      "ad-hoc",
      "monthly",
      "weekly",
    ]);
  });

  test("bundles the substack-author skill via a file ref", () => {
    expect(manifest.skills).toHaveLength(1);
    const skill = manifest.skills?.[0];
    expect(skill?.name).toBe("substack-author");
    expect(skill?.files).toEqual(["skills/substack-author/SKILL.md"]);
  });

  test("declares the substack-api mcpServer for documentation", () => {
    expect(manifest.mcpServers).toHaveLength(1);
    const m = manifest.mcpServers?.[0];
    expect(m?.name).toBe("substack-api");
    expect(m?.transport).toBe("stdio");
    expect((m as { command?: string })?.command).toBe("npx");
  });

  test("scripts wire post/preuninstall", () => {
    expect(manifest.scripts?.postinstall).toBe("./scripts/postinstall.ts");
    expect(manifest.scripts?.preuninstall).toBe("./scripts/preuninstall.ts");
  });

  test("settings declare the three SUBSTACK_* fields", () => {
    const keys = Object.keys(manifest.settings ?? {});
    expect(keys).toContain("substack_publication_url");
    expect(keys).toContain("substack_session_token");
    expect(keys).toContain("substack_user_id");
    // Settings keys must be filesystem-safe identifiers; the regex is
    // /^[a-z][a-z0-9_]{0,63}$/. Spot-check it here so we fail the test
    // if someone renames to a TitleCase / hyphenated key by mistake.
    for (const k of keys) {
      expect(k).toMatch(/^[a-z][a-z0-9_]{0,63}$/);
    }
  });

  test("permissions cover storage + llm + network + shell", () => {
    expect(manifest.permissions.storage).toBe(true);
    expect(manifest.permissions.llm?.providers).toContain("anthropic");
    expect(manifest.permissions.network).toEqual(["*"]);
    expect(manifest.permissions.shell).toBe(true);
  });

  test("does NOT request permissions.env (credentials live in settings)", () => {
    // SUBSTACK_SESSION_TOKEN matches the host's ENV_KEY_LEAK_PATTERN,
    // and substack-pilot is not bundled — `checkEnvKeyLeakInstallGate`
    // would refuse install if we asked for env. lib/substack.ts reads
    // the values from `ctx.invocationMetadata.settings`, so an env
    // grant is both unused AND a blocker. Inferred manifest type omits
    // the property entirely; cast to a wider shape to assert at runtime.
    const perms = manifest.permissions as Record<string, unknown>;
    expect(perms.env).toBeUndefined();
  });

  test("settings expose presence-validated SUBSTACK_* fields", () => {
    const s = manifest.settings ?? {};
    const url = s.substack_publication_url as { type: string; pattern?: string };
    const tok = s.substack_session_token as { type: string; pattern?: string };
    const uid = s.substack_user_id as { type: string; pattern?: string };
    expect(url.type).toBe("text");
    expect(url.pattern).toBeDefined();
    // session-token + user-id MUST have a presence pattern — empty-string
    // paste otherwise reaches substack-mcp and 401s with a cryptic error.
    expect(tok.type).toBe("text");
    expect(tok.pattern).toBeDefined();
    expect(uid.type).toBe("text");
    expect(uid.pattern).toBeDefined();
  });
});

describe("substack-pilot — host validator", () => {
  test("validateManifestV2 accepts the manifest with no errors", () => {
    const result = validateManifestV2(manifest);
    if (!result.valid) {
      // Surface the actual errors in the assertion message so a future
      // failure points at the offending field directly.
      throw new Error(
        `validateManifestV2 rejected manifest:\n  ${result.errors.join("\n  ")}`,
      );
    }
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
  });
});
