#!/usr/bin/env bun
// substack-pilot — JSON-RPC tool dispatcher.
//
// Phase 7 of the defineEntity SDK port: the 5 post-type CRUD tools
// previously registered here (`list_post_types`, `get_post_type`,
// `create_post_type`, `update_post_type`, `delete_post_type`) are now
// auto-generated by the SDK from the `entities` declaration in
// `ezcorp.config.ts`. The host's dispatcher short-circuits those tool
// names to the SDK handler BEFORE reaching this subprocess — see
// `src/extensions/tool-executor.ts:executeToolCall` for the routing
// branch and `src/extensions/registry.ts:buildEntityRegisteredTools`
// for the tool-surface merge.
//
// What's left here: the two bespoke tools that aren't auto-generated
// (`summarize_urls`, `generate_substack_draft`). The latter reads post
// types from the SDK's managed namespace via `lib/substack.ts`'s
// `getPostType` helper (no more `lib/post-types.ts`).

import {
  createToolDispatcher,
  getChannel,
  type ToolHandler,
} from "@ezcorp/sdk/runtime";
import { summarizeUrls } from "./lib/summarize";
import { generateSubstackDraft } from "./lib/substack";
import type { ToolHandlerContext } from "@ezcorp/sdk/runtime";

// ── Tool handlers ───────────────────────────────────────────────

const summarize_urls: ToolHandler = async (args) =>
  summarizeUrls(args as { urls?: unknown; maxWordsPerSummary?: unknown });

const generate_substack_draft: ToolHandler = async (args, ctx) =>
  generateSubstackDraft(
    args as Record<string, unknown>,
    ctx as ToolHandlerContext | undefined,
  );

// ── Exported map for tests ──────────────────────────────────────

export const tools: Record<string, ToolHandler> = {
  summarize_urls,
  generate_substack_draft,
};

// ── Production wiring ───────────────────────────────────────────
// Extracted so tests can cover the wiring branch (the `import.meta.main`
// gate alone is dead under `bun test`). Mirrors the `start()` pattern
// used by substack-engagement/index.ts and web-search/index.ts.
export function start(): void {
  const ch = getChannel();
  createToolDispatcher(tools);
  ch.start();
}

// Gated on `import.meta.main` so test imports don't open stdin.
if (import.meta.main) start();
